CREATE TABLE `battle_history_raw_morden`  (
  `id` int(9) NOT NULL AUTO_INCREMENT,
  `battle_queue_id` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `summoner_id` int(11) NOT NULL,
  `summoner_level` tinyint(4) NOT NULL,
  `monster_1_id` int(11) NOT NULL,
  `monster_1_level` tinyint(4) NOT NULL,
  `monster_1_abilities` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_2_id` int(11) NULL DEFAULT NULL,
  `monster_2_level` tinyint(4) NULL DEFAULT NULL,
  `monster_2_abilities` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_3_id` int(11) NULL DEFAULT NULL,
  `monster_3_level` tinyint(4) NULL DEFAULT NULL,
  `monster_3_abilities` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_4_id` int(11) NULL DEFAULT NULL,
  `monster_4_level` tinyint(4) NULL DEFAULT NULL,
  `monster_4_abilities` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_5_id` int(11) NULL DEFAULT NULL,
  `monster_5_level` tinyint(4) NULL DEFAULT NULL,
  `monster_5_abilities` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_6_id` int(11) NULL DEFAULT NULL,
  `monster_6_level` tinyint(4) NULL DEFAULT NULL,
  `monster_6_abilities` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `created_date` varchar(25) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `created_date_day` varchar(12) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `match_type` varchar(20) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `mana_cap` int(11) NOT NULL,
  `ruleset` varchar(80) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `inactive` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `player_rating_initial` int(11) NOT NULL,
  `player_rating_final` int(11) NOT NULL,
  `winner` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `battle_queue_id_lost` varchar(40) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  `summoner_id_lost` int(11) NOT NULL,
  `summoner_level_lost` tinyint(4) NOT NULL,
  `monster_1_id_lost` int(11) NOT NULL,
  `monster_1_level_lost` tinyint(4) NOT NULL,
  `monster_1_abilities_lost` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_2_id_lost` int(11) NULL DEFAULT NULL,
  `monster_2_level_lost` tinyint(4) NULL DEFAULT NULL,
  `monster_2_abilities_lost` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_3_id_lost` int(11) NULL DEFAULT NULL,
  `monster_3_level_lost` tinyint(4) NULL DEFAULT NULL,
  `monster_3_abilities_lost` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_4_id_lost` int(11) NULL DEFAULT NULL,
  `monster_4_level_lost` tinyint(4) NULL DEFAULT NULL,
  `monster_4_abilities_lost` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_5_id_lost` int(11) NULL DEFAULT NULL,
  `monster_5_level_lost` tinyint(4) NULL DEFAULT NULL,
  `monster_5_abilities_lost` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `monster_6_id_lost` int(11) NULL DEFAULT NULL,
  `monster_6_level_lost` tinyint(4) NULL DEFAULT NULL,
  `monster_6_abilities_lost` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NULL DEFAULT NULL,
  `player_rating_initial_lost` int(11) NOT NULL,
  `player_rating_final_lost` int(11) NOT NULL,
  `loser` varchar(50) CHARACTER SET utf8 COLLATE utf8_general_ci NOT NULL,
  PRIMARY KEY (`id`) USING BTREE,
  INDEX `index_created_date_day`(`created_date_day`) USING BTREE,
  INDEX `index_lost_team`(`summoner_id_lost`, `monster_1_id_lost`, `monster_2_id_lost`, `monster_3_id_lost`, `monster_4_id_lost`, `monster_5_id_lost`, `monster_6_id_lost`) USING BTREE,
  INDEX `index_mana_sum_rule`(`mana_cap`, `summoner_id`, `ruleset`) USING BTREE
) ENGINE = MYISAM CHARACTER SET = utf8 COLLATE = utf8_general_ci ROW_FORMAT = Dynamic ;
ALTER TABLE `battle_history_raw_morden` ADD UNIQUE (`battle_queue_id`);